CommonsEvents.UI/Models/DayViewModel.cs
using System.Collections.Generic;

namespace CommonsEvents.UI.Models
{
    public class DayViewModel
    {
        public string Date { get; set; }
        public IList<EventViewModel> Events { get; set; }
    }
}

CommonsEvents.UI/Models/ErrorViewModel.cs
namespace CommonsEvents.UI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CommonsEvents.UI/Models/EventViewModel.cs
namespace CommonsEvents.UI.Models
{
    public class EventViewModel
    {
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public string MemberIds { get; set; }
    }
}

CommonsEvents.UI/Models/WeekViewModel.cs
using System.Collections.Generic;

namespace CommonsEvents.UI.Models
{
    public class WeekViewModel
    {
        public IList<DayViewModel> Days { get; set; }
    }
}

CommonsEvents.UI/Controllers/EventsController.cs
using System;
using System.Linq;
using CommonsEvents.Business.Services.Interfaces;
using CommonsEvents.UI.Mappers.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace CommonsEvents.UI.Controllers
{
    public class EventsController : Controller
    {
        private readonly IEventService _eventService;
        private readonly IWeekMapper _weekMapper;

        public EventsController(IEventService eventService, IWeekMapper weekMapper)
        {
            _eventService = eventService;
            _weekMapper = weekMapper;
        }

        [HttpGet]
        [Route("Events/GetWeekEvents")]
        public IActionResult GetWeekEvents(DateTime? date)
        {
            if (!date.HasValue)
            {
                date = DateTime.Today;
            }

            var events = _eventService.GetEventsForWeek(date.Value).ToList();
            var viewModel = _weekMapper.Map(events);

            return Ok(viewModel);
        }
    }
}

CommonsEvents.UI/Controllers/MembersController.cs
using System.Linq;
using CommonsEvents.Business.Services.Interfaces;
using CommonsEvents.Domain.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace CommonsEvents.UI.Controllers
{
    public class MembersController : Controller
    {
        private readonly IMemberService _memberService;

        public MembersController(IMemberService memberService)
        {
            _memberService = memberService;
        }

        [HttpGet]
        public ActionResult GetMembers(string memberIds)
        {
            var memberIdsList = memberIds.ParseDashSeparatedList().ToList();
            var members = _memberService.GetMembers(memberIdsList);

            return Ok(members);
        }
    }
}

CommonsEvents.UI/Controllers/WeekController.cs
using Microsoft.AspNetCore.Mvc;

namespace CommonsEvents.UI.Controllers
{
    public class WeekController : Controller
    {
        public IActionResult Events()
        {
            return View();
        }
    }
}

CommonsEvents.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - House of Commons Events</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/bundle.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
        <link rel="stylesheet" href="~/css/bundle.min.css" />
    </environment>
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Week" asp-action="Events">House of Commons Events</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - House of Commons Events
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery/dist/jquery-ui-1.12.1.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>

    <environment include="Development">
        <script src="~/lib/angular.js/angular.js"></script>
        <script src="~/app/commonsevents.module.js"></script>
        <script src="~/app/helpers/datehelper.js"></script>
        <script src="~/app/helpers/httphelper.js"></script>
        <script src="~/app/helpers/urlbuilder.js"></script>
        <script src="~/app/directives/member/member.directive.js"></script>
        <script src="~/app/directives/datepicker/datepicker.directive.js"></script>
        <script src="~/app/directives/event/event.directive.js"></script>
        <script src="~/app/directives/noitems/noitems.directive.js"></script>
        <script src="~/app/directives/day/day.directive.js"></script>
        <script src="~/app/services/commonsevents.events.service.js"></script>
        <script src="~/app/services/commonsevents.members.service.js"></script>
        <script src="~/app/controllers/commonsevents.controller.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/angular.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

CommonsEvents.UI/Views/Week/Events.cshtml
@{
    ViewData["Title"] = "Main Chamber";
}

<h2>@ViewBag.Title</h2>

<div ng-cloak ng-app="commonsevents" ng-modules="commonsevents" ng-controller="eventsController as vm" ng-init="vm.getData()">

    <div>
        <label>Select week</label>
        <date-picker date="vm.date" on-date-change="vm.getData()"></date-picker>
    </div>

    <div ng-repeat="day in vm.data.days">
        <day data="day"></day>
    </div>

    <no-items text="There are no events this week" ng-show="vm.data.days.length === 0"></no-items>
</div>